"""India-Stack code generator.

Produces a list of files (dict with `path` + `content` + `kind`) per selected component.
The output is persisted into the codegen_files collection so they appear in Stage 4 alongside
the LLM-generated service files.
"""
from __future__ import annotations
from typing import Dict, List, Any
from .catalog import by_id, CATALOG  # noqa: F401


# ---------------------------------------------------------------------------
# Tiny templating — avoids dragging Jinja2 in.
# ---------------------------------------------------------------------------
def _fmt(template: str, **vars) -> str:
    out = template
    for k, v in vars.items():
        out = out.replace("{{" + k + "}}", str(v))
    return out


# ---------------------------------------------------------------------------
# Common middleware (audit + consent storage + circuit-breaker).
# Generated once per project (when ANY India-Stack component is selected).
# ---------------------------------------------------------------------------
INDIA_STACK_MIDDLEWARE = '''"""India-Stack common infrastructure: audit log + consent storage + circuit-breaker.

Auto-generated by LAMA. Safe to edit, but the next regeneration will overwrite.
"""
import os
import time
import json
import uuid
import logging
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger("india_stack")

# ─── Consent / Audit storage ────────────────────────────────────────────────
# Replace this in-memory store with your DB collection.
_AUDIT: list[dict] = []
_CONSENTS: dict[str, dict] = {}


def audit(action: str, *, project_id: str = "", user_id: str = "",
          component: str = "", payload: Optional[dict] = None,
          status: str = "ok", error: str = "") -> None:
    """Append-only audit record. ALL India-Stack calls MUST go through this."""
    entry = {
        "id": uuid.uuid4().hex,
        "at": datetime.now(timezone.utc).isoformat(),
        "action": action,
        "component": component,
        "project_id": project_id,
        "user_id": user_id,
        "status": status,
        "error": error,
        "payload": payload or {},
    }
    _AUDIT.append(entry)
    logger.info("india_stack.audit %s %s %s", component, action, status)


def store_consent(consent_id: str, *, kind: str, user_id: str, expires_at: str,
                  meta: Optional[dict] = None) -> None:
    _CONSENTS[consent_id] = {
        "id": consent_id, "kind": kind, "user_id": user_id,
        "granted_at": datetime.now(timezone.utc).isoformat(),
        "expires_at": expires_at, "meta": meta or {},
        "revoked": False,
    }


def get_consent(consent_id: str) -> Optional[dict]:
    return _CONSENTS.get(consent_id)


def revoke_consent(consent_id: str) -> bool:
    c = _CONSENTS.get(consent_id)
    if not c:
        return False
    c["revoked"] = True
    c["revoked_at"] = datetime.now(timezone.utc).isoformat()
    return True


# ─── Circuit-breaker ────────────────────────────────────────────────────────
class CircuitBreaker:
    """Per-component CB. Opens after `threshold` consecutive failures, half-open after `reset_sec`."""

    def __init__(self, name: str, threshold: int = 5, reset_sec: int = 30):
        self.name = name
        self.threshold = threshold
        self.reset_sec = reset_sec
        self.failures = 0
        self.opened_at: float = 0.0

    def allow(self) -> bool:
        if self.failures < self.threshold:
            return True
        if time.time() - self.opened_at > self.reset_sec:
            self.failures = 0  # half-open
            return True
        return False

    def record(self, success: bool):
        if success:
            self.failures = 0
        else:
            self.failures += 1
            if self.failures >= self.threshold:
                self.opened_at = time.time()


BREAKERS: dict[str, CircuitBreaker] = {}


def breaker(name: str) -> CircuitBreaker:
    if name not in BREAKERS:
        BREAKERS[name] = CircuitBreaker(name)
    return BREAKERS[name]


# ─── Provider mode helper ───────────────────────────────────────────────────
def is_mock(component: str) -> bool:
    return os.environ.get(f"{component.upper()}_PROVIDER", "mock").lower() == "mock"
'''


# ---------------------------------------------------------------------------
# Per-component generators.
# All generators return list[dict(path, content, kind, service_name)].
# ---------------------------------------------------------------------------
def _backend_router(component_id: str, name: str, endpoints: list, mode_var: str,
                    consent_kind: str | None) -> str:
    routes = []
    for method, path, desc in endpoints:
        fn_name = path.strip("/").replace("/", "_").replace("{", "").replace("}", "").replace("-", "_")
        body_lines = []
        body_lines.append(f'    """{desc}"""')
        body_lines.append(f'    audit("{component_id}.{fn_name}", payload=payload or {{}}, component="{component_id}")')
        if "mandate" in path or "consent" in path or "request" in path:
            body_lines.append('    consent_id = uuid.uuid4().hex')
            body_lines.append(f'    store_consent(consent_id, kind="{consent_kind or component_id}",')
            body_lines.append('                  user_id=(payload or {}).get("user_id", "anonymous"),')
            body_lines.append('                  expires_at=(datetime.now(timezone.utc) + timedelta(days=30)).isoformat())')
        body_lines.append(f'    if is_mock("{component_id}"):')
        body_lines.append(f'        return mock_response("{component_id}", "{fn_name}", payload)')
        body_lines.append('    # TODO: call provider SDK / HTTP API here')
        body_lines.append(f'    return {{"ok": True, "component": "{component_id}", "endpoint": "{path}"}}')
        param = ", payload: dict | None = None" if method in ("POST", "PUT", "PATCH") else ""
        if "{" in path:
            # path param
            pname = path[path.index("{") + 1: path.index("}")]
            param = f", {pname}: str" + param
            decorator_path = path
        else:
            decorator_path = path
        routes.append(
            f"@router.{method.lower()}(\"{decorator_path}\")\n"
            f"async def {fn_name}(request: Request{param}):\n"
            + "\n".join(body_lines) + "\n"
        )
    return f'''"""India-Stack: {name}
Auto-generated by LAMA. Mock mode by default — set env vars listed in india_stack_config.env to switch to sandbox.
"""
import uuid
from datetime import datetime, timezone, timedelta
from fastapi import APIRouter, Request

from india_stack_common import audit, store_consent, is_mock, breaker

from india_stack_mocks import mock_response

router = APIRouter(prefix="/api", tags=["india-stack:{component_id}"])


''' + "\n\n".join(routes)


def _mock_module() -> str:
    return '''"""Realistic mock responses for India-Stack components. Used when *_PROVIDER=mock."""
import uuid
from datetime import datetime, timezone, timedelta


def mock_response(component: str, action: str, payload: dict | None = None) -> dict:
    payload = payload or {}
    now = datetime.now(timezone.utc).isoformat()

    if component == "aadhaar_ekyc":
        if "initiate" in action:
            return {"ok": True, "transaction_id": uuid.uuid4().hex, "otp_sent": True, "expires_in": 300}
        if "verify" in action:
            return {
                "ok": True, "verified": True,
                "demographics": {
                    "name": "Aarav Sharma", "dob": "1992-05-21", "gender": "M",
                    "address": "MG Road, Bengaluru, KA 560001",
                    "aadhaar_last4": (payload.get("aadhaar_number", "0000000000"))[-4:],
                },
                "photo_b64": "iVBORw0KGgoAAAANSUhEUgAAAA==",
            }
    if component == "aadhaar_esign":
        if "request" in action:
            return {"ok": True, "request_id": uuid.uuid4().hex,
                    "signing_url": "https://mock-esign.local/sign/" + uuid.uuid4().hex[:8]}
        if "callback" in action or "esign_" in action:
            return {"ok": True, "signed": True, "signed_pdf_url": "/static/mock_signed.pdf"}
    if component == "digilocker":
        if "documents" in action:
            return {"ok": True, "documents": [
                {"id": "dl_001", "type": "Driving Licence", "issued_by": "Ministry of Road Transport"},
                {"id": "pan_001", "type": "PAN Card", "issued_by": "Income Tax Department"},
                {"id": "ssc_001", "type": "Class X Marksheet", "issued_by": "CBSE"},
            ]}
        if "document" in action:
            return {"ok": True, "document_b64": "JVBERi0xLjQK%PDF mock", "mime": "application/pdf"}
        if "authorize" in action:
            return {"redirect_url": "https://mock-digilocker.local/oauth"}
    if component == "upi":
        if "collect" in action:
            return {"ok": True, "txn_id": "TXN" + uuid.uuid4().hex[:10].upper(),
                    "status": "REQUESTED", "vpa": payload.get("vpa", "test@upi"),
                    "amount": payload.get("amount", 0)}
        if "intent" in action:
            amt = payload.get("amount", 0)
            return {"ok": True, "intent": f"upi://pay?pa=merchant@upi&pn=Demo&am={amt}&tn=Demo",
                    "qr_b64": "QR_PLACEHOLDER"}
        if "mandate" in action:
            return {"ok": True, "mandate_id": "MAN" + uuid.uuid4().hex[:10].upper(), "status": "PENDING"}
        if "webhook" in action:
            return {"ok": True, "received": True}
        if "txn" in action:
            return {"ok": True, "status": "SUCCESS", "rrn": uuid.uuid4().hex[:12].upper(), "ts": now}
    if component == "bbps":
        if "billers" in action:
            return {"ok": True, "billers": [
                {"id": "BSES_RAJDHANI", "name": "BSES Rajdhani Power", "category": "Electricity"},
                {"id": "IGL", "name": "Indraprastha Gas Ltd", "category": "Gas"},
                {"id": "FASTAG_HDFC", "name": "FASTag HDFC Bank", "category": "FASTag"},
            ]}
        if "fetch" in action:
            return {"ok": True, "bill_amount": 1248.50, "due_date": "2026-06-15",
                    "consumer_name": "Aarav Sharma", "bill_number": "BIL" + uuid.uuid4().hex[:6].upper()}
        if "pay" in action:
            return {"ok": True, "txn_id": "BBPS" + uuid.uuid4().hex[:10].upper(),
                    "status": "SUCCESS", "approval_ref": uuid.uuid4().hex[:12].upper()}
        if "receipt" in action:
            return {"ok": True, "receipt_url": "/static/mock_bbps_receipt.pdf"}
    if component == "account_aggregator":
        if "consent" in action and "data" not in action:
            return {"ok": True, "consent_handle": uuid.uuid4().hex,
                    "status": "REQUESTED",
                    "redirect_url": "https://mock-aa.local/consent/" + uuid.uuid4().hex[:8]}
        if "data-request" in action or "data_request" in action:
            return {"ok": True, "session_id": uuid.uuid4().hex, "status": "ACTIVE"}
        if "data" in action:
            return {"ok": True, "accounts": [
                {"masked_account": "XXXX1234", "bank": "HDFC Bank", "type": "SAVINGS",
                 "balance": 124350.75, "transactions": [
                    {"date": "2026-05-01", "amount": -1200, "narration": "UPI to Zomato"},
                    {"date": "2026-05-03", "amount":  80000, "narration": "Salary credit"},
                 ]},
            ]}
        if "notify" in action:
            return {"ok": True, "ack": True}
    if component == "meripehchaan":
        if "login" in action:
            return {"redirect_url": "https://mock-meripehchaan.local/oauth?client_id=demo"}
        if "callback" in action:
            return {"ok": True, "user": {"id": uuid.uuid4().hex, "name": "Aarav Sharma", "email": "demo@gov.in"}}
    return {"ok": True, "mock": True, "component": component, "action": action, "ts": now}
'''


def _frontend_component(component_id: str, name: str) -> tuple[str, str]:
    """Return (path, jsx_content) for a frontend React component."""
    title = name.split("(")[0].strip()
    pascal = "".join(part.capitalize() for part in component_id.split("_"))
    jsx = f'''import React, {{ useState }} from "react";
// LAMA: India-Stack component for {title}
// Calls the auto-generated backend at /api/india/* — switch mock→sandbox via env vars.

export default function {pascal}Widget() {{
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError]   = useState("");

  const run = async () => {{
    setLoading(true); setError(""); setResult(null);
    try {{
      // TODO: replace with the real endpoint for {component_id}
      const r = await fetch(`${{process.env.REACT_APP_BACKEND_URL}}/api/india/{component_id}/demo`, {{ method: "POST" }});
      const data = await r.json();
      setResult(data);
    }} catch (e) {{
      setError(String(e));
    }} finally {{ setLoading(false); }}
  }};

  return (
    <div className="p-4 border border-[#E6E6E6] rounded-sm bg-white" data-testid="india-stack-{component_id}">
      <h3 className="text-sm font-bold mb-2">{title}</h3>
      <button onClick={{run}} disabled={{loading}}
              className="text-xs bg-[#FFE600] text-[#2E2E38] font-bold px-3 py-1 rounded-sm">
        {{loading ? "Running…" : "Run {title}"}}
      </button>
      {{error && <div className="text-xs text-rose-700 mt-2">{{error}}</div>}}
      {{result && (
        <pre className="text-[10px] font-mono mt-2 bg-[#FAFAFC] p-2 overflow-auto max-h-64">
{{JSON.stringify(result, null, 2)}}
        </pre>
      )}}
    </div>
  );
}}
'''
    return (f"frontend/src/components/india_stack/{pascal}Widget.jsx", jsx)


def _env_block(selected: list[dict]) -> str:
    lines = [
        "# India-Stack configuration generated by LAMA.",
        "# Default mode is `mock` — set <COMPONENT>_PROVIDER to a real value to switch to sandbox.",
        "",
    ]
    for sel in selected:
        cat = by_id(sel["component_id"])
        if not cat:
            continue
        lines.append(f"# ── {cat['name']} ──")
        for var, hint in cat["env_vars"]:
            current = sel.get("env", {}).get(var, "")
            lines.append(f"{var}={current}    # {hint}")
        lines.append("")
    return "\n".join(lines)


def _compliance_tests(selected: list[dict]) -> str:
    ids = [s["component_id"] for s in selected]
    return f'''"""Compliance test fixtures for India-Stack integrations.

These tests verify:
  • Every selected component has audit logging for every endpoint.
  • Consent records carry a non-empty `kind` + `user_id` and a future `expires_at`.
  • Mock mode does NOT leak real PII (Aadhaar last-4 only, no full number).
  • Circuit-breaker opens after threshold failures.

Run with: pytest -v tests/test_india_stack_compliance.py
"""
import pytest
from india_stack_common import _AUDIT, _CONSENTS, BREAKERS, audit, store_consent, breaker

SELECTED = {ids!r}


@pytest.fixture(autouse=True)
def _reset():
    _AUDIT.clear(); _CONSENTS.clear(); BREAKERS.clear()


def test_audit_writes_records():
    for comp in SELECTED:
        audit("test.call", component=comp, payload={{"x": 1}})
    assert len(_AUDIT) == len(SELECTED)
    for entry in _AUDIT:
        assert entry["component"] in SELECTED
        assert entry["at"], "audit entry must carry a timestamp"


def test_consent_required_fields():
    store_consent("c1", kind="ekyc", user_id="u1", expires_at="2099-01-01T00:00:00Z")
    c = _CONSENTS["c1"]
    assert c["kind"] and c["user_id"] and c["expires_at"] > "2026-01-01"


def test_circuit_breaker_opens():
    cb = breaker("dummy")
    for _ in range(cb.threshold):
        cb.record(False)
    assert cb.allow() is False, "CB should be open after threshold failures"
'''


def generate_for_project(selected: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Generate all files for the supplied list of selections.

    selected = [{component_id, attach_to (service_name|'new'), mode, sandbox_provider, env}, …]
    """
    files: List[Dict[str, Any]] = []
    if not selected:
        return files

    # Common infra (only emitted when at least one component is selected).
    files.append({
        "path": "backend/india_stack_common.py",
        "content": INDIA_STACK_MIDDLEWARE,
        "kind": "infra",
        "service_name": "india-stack",
    })
    files.append({
        "path": "backend/india_stack_mocks.py",
        "content": _mock_module(),
        "kind": "infra",
        "service_name": "india-stack",
    })
    files.append({
        "path": "backend/india_stack_config.env",
        "content": _env_block(selected),
        "kind": "config",
        "service_name": "india-stack",
    })
    files.append({
        "path": "backend/tests/test_india_stack_compliance.py",
        "content": _compliance_tests(selected),
        "kind": "test",
        "service_name": "india-stack",
    })

    for sel in selected:
        cat = by_id(sel["component_id"])
        if not cat:
            continue
        target_service = sel.get("attach_to") or "india-stack"

        # Backend router
        files.append({
            "path": f"backend/india/{cat['id']}_router.py",
            "content": _backend_router(
                cat["id"], cat["name"], cat["endpoints"],
                f"{cat['id'].upper()}_PROVIDER", cat.get("consent_kind"),
            ),
            "kind": "backend",
            "service_name": target_service,
        })
        # Frontend widget
        path, content = _frontend_component(cat["id"], cat["name"])
        files.append({
            "path": path, "content": content,
            "kind": "frontend", "service_name": target_service,
        })

    # Aggregator that mounts every router on the FastAPI app.
    mount = ["from fastapi import FastAPI", ""]
    for sel in selected:
        cat = by_id(sel["component_id"])
        if not cat:
            continue
        mount.append(f"from india.{cat['id']}_router import router as {cat['id']}_router")
    mount.append("")
    mount.append("def mount_india_stack(app: FastAPI) -> None:")
    if not selected:
        mount.append("    return")
    else:
        for sel in selected:
            cat = by_id(sel["component_id"])
            if not cat:
                continue
            mount.append(f"    app.include_router({cat['id']}_router)")
    files.append({
        "path": "backend/india_stack_mount.py",
        "content": "\n".join(mount) + "\n",
        "kind": "infra",
        "service_name": "india-stack",
    })
    return files
